name = "GaussianIntegers"
uuid = "814f2dd7-e056-4194-98c2-60692011a20c"
authors = ["Ulrich Thiel <thiel@mathematik.uni-kl.de>"]
version = "0.2.1"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
AbstractAlgebra = "0.27"
